apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- tekton.yaml
- shipwright.yaml
# strategies
- https://raw.githubusercontent.com/shipwright-io/build/main/samples/buildstrategy/kaniko/buildstrategy_kaniko_cr.yaml
