# Source: mutating-webhook/templates/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spire-mutating-webhook
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
spec:
  secretName: spire-mutating-webhook-tls
  dnsNames:
  - spire-mutating-webhook
  - spire-mutating-webhook.spire
  - spire-mutating-webhook.spire.svc
  - spire-mutating-webhook.spire.svc.cluster
  - spire-mutating-webhook.spire.svc.cluster.local
  isCA: false
  duration: 720h0m0s
  renewBefore: 120h0m0s
  issuerRef:
    name: spire-mutating-webhook-issuer
    kind: Issuer
---
# Source: mutating-webhook/templates/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: spire-mutating-webhook-issuer
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
spec:
  selfSigned: {}
