# Source: mutating-webhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-mutating-webhook
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
---
# Source: mutating-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spire-mutating-webhook
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
---
# Source: mutating-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-mutating-webhook
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spire-mutating-webhook
      app.kubernetes.io/instance: spire-mutating-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spire-mutating-webhook
        app.kubernetes.io/instance: spire-mutating-webhook
    spec:
      serviceAccountName: spire-mutating-webhook
      securityContext: {}
      volumes:
      - name: certs
        secret:
          secretName: spire-mutating-webhook-tls
      containers:
      - name: mutating-webhook
        securityContext: {}
        image: "mutating-webhook:1.0.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        volumeMounts:
        - name: certs
          mountPath: "/certs"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /_healthz
            port: https
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /_ready
            port: https
            scheme: HTTPS
        resources: {}
