apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: spire-mutating-webhook
  namespace: spire
  labels:
    app.kubernetes.io/name: spire-mutating-webhook
    app.kubernetes.io/instance: spire-mutating-webhook
  annotations:
    cert-manager.io/inject-ca-from: spire/spire-mutating-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    namespaceSelector:
      null
    clientConfig:
      service:
        name: spire-mutating-webhook
        namespace: spire
        path: /mutate
        port: 443
    failurePolicy: Fail
    reinvocationPolicy: Never
    sideEffects: Unknown
    matchPolicy: Equivalent
    name: imagepolicy
    rules:
      null
