apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: datasette
  namespace: web-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - "datasette.happylittlecloud.ca"
    secretName: datasette-tls
  rules:
  - host: "datasette.happylittlecloud.ca"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: datasette
            port:
              number: 80
