variables:
  IMAGE: $DO_REGISTRY_URL/web/landing-page

#################################
#                               #
#   Everything below *should*   #
#   be generic to other apps    #
#                               #
#################################


stages:
- build
- template
- release
- update

### Testing

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
    - docker build .

template:
  image:
    name: alpine/helm
    entrypoint: [""]
  stage: template
  script:
    - helm template ./chart | grep -v '^  *$' | tee manifest.yaml
  artifacts:
    paths:
    - manifest.yaml

### Master only
    
release:
  stage: release
  image: docker:latest
  services:
  - docker:dind
  dependencies:
    - build
  before_script:
    - mkdir -p $HOME/.docker
    - cat $DO_REGISTRY_TOKEN > $HOME/.docker/config.json
  script:
    - docker build . -t $IMAGE
    - docker push $IMAGE
  only:
    - master

update:
  stage: update
  dependencies:
    - template
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  script:
  - kubectl --kubeconfig="$KUBE_CONF" apply -f manifest.yaml
  only:
    - master
