apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: istio-egress
  chartHome: ../istio-charts/gateways/
