apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

generatorOptions:
  disableNameSuffixHash: true

helmChartInflationGenerator:
- chartName: base
  chartHome: ./istio-charts/
  releaseName: istio
#- chartName: istio-discovery
#  chartHome: ./istio-charts/istio-control/
#  releaseName: istiod

- chartName: istio-ingress
  chartHome: ./istio-charts/gateways/
  values: ingress-gateway-values.yaml
#- chartName: istio-egress
#  chartHome: ./istio-charts/gateways/
