apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
- https://github.com/blairdrummond/minio-gateway-opa/base

replicas:
- name: minio-gateway-opa
  count: 1

patchesJson6902:
- target:
    version: v1
    kind: StatefulSet
    name: minio-gateway-opa
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value: {}
- target:
    version: v1
    kind: StatefulSet
    name: minio-gateway-etcd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value: {}

patchesStrategicMerge:
- |-
  apiVersion: networking.istio.io/v1alpha3
  kind: DestinationRule
  metadata:
    name: minio-gateway-etcd
  $patch: delete
#- |-
#   apiVersion: apps/v1
#   kind: Deployment
#   metadata:
#     name: minio-gateway
#   spec:
#     template:
#       spec:
#         containers:
#           - name: minio
#             env:
#               - name: MINIO_IDENTITY_OPENID_CONFIG_URL
#                 valueFrom:
#                   secretKeyRef:
#                     name: minio-gateway-openid-secret
#                     key: MINIO_IDENTITY_OPENID_CONFIG_URL
#               - name: MINIO_IDENTITY_OPENID_CLIENT_ID
#                 valueFrom:
#                   secretKeyRef:
#                     name: minio-gateway-openid-secret
#                     key: MINIO_IDENTITY_OPENID_CLIENT_ID
