apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# RBAC
- account.yaml
- cluster-role.yaml

# Agent daemonset & CSI Driver
- configmap.yaml
- daemonset.yaml
- spiffe-csi-driver.yaml
