apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: false
  externalDatabase:
    enabled: true
  podDisruptionBudget:
    enabled: true
