apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# RBAC
- server-cluster-role.yaml
- server-account.yaml

# Services/Ingress
- ingress.yaml
- server-service.yaml
- server-oidc-service.yaml

# Settings
- oidc-dp-configmap.yaml
- spire-bundle-configmap.yaml
- server-configmap.yaml

# Server
- server-statefulset.yaml
