apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/do-loadbalancer-name: "happylittlecloud.ca"
          service.beta.kubernetes.io/do-loadbalancer-certificate-id: "your-certificate-id"
          service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
          service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
