apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  profile: default
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/do-loadbalancer-name: "happylittlecloud"
          service.beta.kubernetes.io/do-loadbalancer-hostname: "workaround.happylittlecloud.ca"
          service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: 'true'
  addonComponents:
    grafana:
      enabled: true
    kiali:
      enabled: true
