apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: 'https://kiali.org/helm-charts'
    chart: kiali-operator
    helm:
      values: |
        cr:
          create: true
          namespace: istio-system
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kiali-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
