apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  deployment:
    ingress:
      enabled: false
  prometheus:
    url: http://kube-prometheus-stack-prometheus.monitoring-system.svc.cluster.local:9090
