variables:
  IMAGE: $DO_REGISTRY_URL/web/bdrummond

stages:
- build
- template
- release
- deploy

include:
  - project: "happylittlecloud/ci-templates"
    file: "/build-release.yaml"
  - project: "happylittlecloud/ci-templates"
    file: "/template-deploy.yaml"
