apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply CRDs first
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

resources:
- keycloak.org_keycloakbackups_crd.yaml
- keycloak.org_keycloakclients_crd.yaml
- keycloak.org_keycloakrealms_crd.yaml
- keycloak.org_keycloaks_crd.yaml
- keycloak.org_keycloakusers_crd.yaml
