apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: s3-bucket-sync
spec:
  entrypoint: s3-bucket-sync
  serviceAccountName: argo
  arguments:
    parameters:
      - name: git-repo
        value: https://github.com/blairdrummond/happylittlecloud.ca.git
      - name: git-path
        value: s3-bucket
      - name: git-revision
        value: main
  templates:
  # Tie together the two templates below
  - name: s3-bucket-sync
    steps:
    - - name: mc-mirror
        template: mc-mirror
    - - name: cdn-flush
        template: cdn-flush

  # MC Mirror from git repo
  - name: mc-mirror
    inputs:
      artifacts:
      - name: repo-source
        path: /src
        git:
          repo: "{{workflow.parameters.git-repo}}"
          revision: "{{workflow.parameters.git-revision}}"
    container:
      image: minio/mc
      command: [sh, -c]
      args: ['
        mc config host add do $SPACES_URL $SPACES_KEY $SPACES_SECRET ;
        mc diff /src/{{workflow.parameters.git-path}}/ do/$SPACES_BUCKET/ ;
        mc mirror --overwrite /src/{{workflow.parameters.git-path}}/ do/$SPACES_BUCKET/
      ']
      workingDir: /src
      env:
      - name: SPACES_URL
        valueFrom:
          secretKeyRef:
            name: spaces-secret
            key: url
      - name: SPACES_BUCKET
        valueFrom:
          secretKeyRef:
            name: spaces-secret
            key: bucket
      - name: SPACES_KEY
        valueFrom:
          secretKeyRef:
            name: spaces-secret
            key: key
      - name: SPACES_SECRET
        valueFrom:
          secretKeyRef:
            name: spaces-secret
            key: secret

  # Flush and re-cache everything in the CDN
  - name: cdn-flush
    container:
      image: digitalocean/doctl
      args:
      - compute
      - cdn
      - flush
      - $(DO_CDN_ID)
      - -t
      - $(DO_TOKEN)
      env:
      - name: DO_TOKEN
        valueFrom:
          secretKeyRef:
            name: do-token
            key: token
      - name: DO_CDN_ID
        valueFrom:
          secretKeyRef:
            name: do-token
            key: cdn-id
