apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: platform
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.0.15
    chart: ingress-nginx
    #         service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
    #         service.beta.kubernetes.io/do-loadbalancer-tls-passthrough: "true"
    helm:
      values: |
        controller:
          service:
            annotations:
              service.beta.kubernetes.io/do-loadbalancer-name: happylittlecloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
