apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
  namespace: argocd
spec:
  hosts:
  - argocd.happylittlecloud.ca
  gateways:
  - istio-system/ingressgateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: argocd-server.argocd.svc.cluster.local
