apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifest.yaml
- ingress.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: nginx-conf
  files:
  - nginx.conf
